---
title: CSS Properties Reference
slug: orphaned/Web/CSS/CSS_Properties_Reference
tags:
  - CSS
  - Estilos
  - Propiedades
  - Referencia
translation_of: Web/CSS/CSS_Properties_Reference
original_slug: Web/CSS/CSS_Properties_Reference
---
<h2 id="Propiedades_CSS_Básicas_Referencia">Propiedades CSS Básicas Referencia</h2>

<p>La siguiente lista es una lista de la propiedades CSS más comunes junto con su equivalente en notación DOM que es cómo son normalmente accedidas desde JavaScript.</p>

<div class="note"><strong>Note:</strong>  Es una lista incompleta. Para descubrir más propiedades CSS visita  <a href="/es-ES/docs/Web/CSS/Reference">la referencia principal CSS </a>y  and <a class="internal" href="/es-ES/docs/Web/CSS/Mozilla_Extensions">las Extensiones CSS de Mozilla</a>. Los artículos de referencia incluyen ejemplos sobre cómo usar todas estas propiedades.</div>

<table>
 <thead>
  <tr>
   <th scope="col"><strong>CSS</strong></th>
   <th scope="col"><strong>JavaScript</strong></th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>background</td>
   <td>background</td>
  </tr>
  <tr>
   <td>background-attachment</td>
   <td>backgroundAttachment</td>
  </tr>
  <tr>
   <td>background-color</td>
   <td>backgroundColor</td>
  </tr>
  <tr>
   <td>background-image</td>
   <td>backgroundImage</td>
  </tr>
  <tr>
   <td>background-position</td>
   <td>backgroundPosition</td>
  </tr>
  <tr>
   <td>background-repeat</td>
   <td>backgroundRepeat</td>
  </tr>
  <tr>
   <td>border</td>
   <td>border</td>
  </tr>
  <tr>
   <td>border-bottom</td>
   <td>borderBottom</td>
  </tr>
  <tr>
   <td>border-bottom-color</td>
   <td>borderBottomColor</td>
  </tr>
  <tr>
   <td>border-bottom-style</td>
   <td>borderBottomStyle</td>
  </tr>
  <tr>
   <td>border-bottom-width</td>
   <td>borderBottomWidth</td>
  </tr>
  <tr>
   <td>border-color</td>
   <td>borderColor</td>
  </tr>
  <tr>
   <td>border-left</td>
   <td>borderLeft</td>
  </tr>
  <tr>
   <td>border-left-color</td>
   <td>borderLeftColor</td>
  </tr>
  <tr>
   <td>border-left-style</td>
   <td>borderLeftStyle</td>
  </tr>
  <tr>
   <td>border-left-width</td>
   <td>borderLeftWidth</td>
  </tr>
  <tr>
   <td>border-right</td>
   <td>borderRight</td>
  </tr>
  <tr>
   <td>border-right-color</td>
   <td>borderRightColor</td>
  </tr>
  <tr>
   <td>border-right-style</td>
   <td>borderRightStyle</td>
  </tr>
  <tr>
   <td>border-right-width</td>
   <td>borderRightWidth</td>
  </tr>
  <tr>
   <td>border-style</td>
   <td>borderStyle</td>
  </tr>
  <tr>
   <td>border-top</td>
   <td>borderTop</td>
  </tr>
  <tr>
   <td>border-top-color</td>
   <td>borderTopColor</td>
  </tr>
  <tr>
   <td>border-top-style</td>
   <td>borderTopStyle</td>
  </tr>
  <tr>
   <td>border-top-width</td>
   <td>borderTopWidth</td>
  </tr>
  <tr>
   <td>border-width</td>
   <td>borderWidth</td>
  </tr>
  <tr>
   <td>clear</td>
   <td>clear</td>
  </tr>
  <tr>
   <td>clip</td>
   <td>clip</td>
  </tr>
  <tr>
   <td>color</td>
   <td>color</td>
  </tr>
  <tr>
   <td>cursor</td>
   <td>cursor</td>
  </tr>
  <tr>
   <td>display</td>
   <td>display</td>
  </tr>
  <tr>
   <td>filter</td>
   <td>filter</td>
  </tr>
  <tr>
   <td>float</td>
   <td>cssFloat</td>
  </tr>
  <tr>
   <td>font</td>
   <td>font</td>
  </tr>
  <tr>
   <td>font-family</td>
   <td>fontFamily</td>
  </tr>
  <tr>
   <td>font-size</td>
   <td>fontSize</td>
  </tr>
  <tr>
   <td>font-variant</td>
   <td>fontVariant</td>
  </tr>
  <tr>
   <td>font-weight</td>
   <td>fontWeight</td>
  </tr>
  <tr>
   <td>height</td>
   <td>height</td>
  </tr>
  <tr>
   <td>left</td>
   <td>left</td>
  </tr>
  <tr>
   <td>letter-spacing</td>
   <td>letterSpacing</td>
  </tr>
  <tr>
   <td>line-height</td>
   <td>lineHeight</td>
  </tr>
  <tr>
   <td>list-style</td>
   <td>listStyle</td>
  </tr>
  <tr>
   <td>list-style-image</td>
   <td>listStyleImage</td>
  </tr>
  <tr>
   <td>list-style-position</td>
   <td>listStylePosition</td>
  </tr>
  <tr>
   <td>list-style-type</td>
   <td>listStyleType</td>
  </tr>
  <tr>
   <td>margin</td>
   <td>margin</td>
  </tr>
  <tr>
   <td>margin-bottom</td>
   <td>marginBottom</td>
  </tr>
  <tr>
   <td>margin-left</td>
   <td>marginLeft</td>
  </tr>
  <tr>
   <td>margin-right</td>
   <td>marginRight</td>
  </tr>
  <tr>
   <td>margin-top</td>
   <td>marginTop</td>
  </tr>
  <tr>
   <td>overflow</td>
   <td>overflow</td>
  </tr>
  <tr>
   <td>padding</td>
   <td>padding</td>
  </tr>
  <tr>
   <td>padding-bottom</td>
   <td>paddingBottom</td>
  </tr>
  <tr>
   <td>padding-left</td>
   <td>paddingLeft</td>
  </tr>
  <tr>
   <td>padding-right</td>
   <td>paddingRight</td>
  </tr>
  <tr>
   <td>padding-top</td>
   <td>paddingTop</td>
  </tr>
  <tr>
   <td>page-break-after</td>
   <td>pageBreakAfter</td>
  </tr>
  <tr>
   <td>page-break-before</td>
   <td>pageBreakBefore</td>
  </tr>
  <tr>
   <td>position</td>
   <td>position</td>
  </tr>
  <tr>
   <td>stroke-dasharray</td>
   <td>strokeDasharray</td>
  </tr>
  <tr>
   <td>stroke-dashoffset</td>
   <td>strokeDashoffset</td>
  </tr>
  <tr>
   <td>stroke-width</td>
   <td>strokeWidth</td>
  </tr>
  <tr>
   <td>text-align</td>
   <td>textAlign</td>
  </tr>
  <tr>
   <td>text-decoration</td>
   <td>textDecoration</td>
  </tr>
  <tr>
   <td>text-indent</td>
   <td>textIndent</td>
  </tr>
  <tr>
   <td>text-transform</td>
   <td>textTransform</td>
  </tr>
  <tr>
   <td>top</td>
   <td>top</td>
  </tr>
  <tr>
   <td>vertical-align</td>
   <td>verticalAlign</td>
  </tr>
  <tr>
   <td>visibility</td>
   <td>visibility</td>
  </tr>
  <tr>
   <td>width</td>
   <td>width</td>
  </tr>
  <tr>
   <td>z-index</td>
   <td>zIndex</td>
  </tr>
 </tbody>
</table>
